In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("TridentTreatsSupermarket2025_totally_real_not_fabricated.csv")

In [3]:
data = pd.read_csv("TridentTreatsSupermarket2025_totally_real_not_fabricated.csv")

In [4]:
data.head

<bound method NDFrame.head of                   Name                         Email Address Nickname  \
0          José Clarke        kendrabest760@tridenttreats.bb    ken41
1        Zoë Callender         aliciajordan285@bdsconnect.bb    ali37
2           Renée Best           omarholder876@bdsconnect.bb    oma22
3      François Holder          devinjordan864@caribmail.com    dev39
4         Mårlon Forde        mårlongittens371@bdsconnect.bb    mår27
..                 ...                                   ...      ...
295       Devin Holder          devinholder102@caribmail.com      NaN
296  Alicia Brathwaite  aliciabrathwaite780@tridenttreats.bb      NaN
297       Tanya Holder         tanyaholder917@islandshop.net    tan96
298       Kendra Hinds         kendrahinds859@islandshop.net    ken73
299      Kendra Clarke         kendraclarke851@caribmail.com    ken73

                                     Home Address    Password      Salt  \
0    36 Grazettes Main Road, St. Philip, Barbados  n](l.2edlB  oGMbJmTP
1              27 Bank Hall, St. Philip, Barbados  lWmTS:Hf~6  Ih7yfJs1
2           72 Country Road, St. Philip, Barbados  6>UuVTA\I`  7RPeMOkI
3       207 Atlantic Shores, St. Philip, Barbados  OZIiB+|OB@  Fz46PDjq
4         127 Two Mile Hill, St. Philip, Barbados  lgot=u^2/i  yyMDHqJ3
..                                            ...         ...       ...
295                                           NaN         NaN       NaN
296                                           NaN         NaN       NaN
297            46 Bank Hall, St. Philip, Barbados  b]!]nY4%[]  fhjzzSLg
298        196 Deacons Road, St. Philip, Barbados  |-.I?ZT8\:  8zFGrjXD
299            7 St. Philip, St. Philip, Barbados  wW:]PtM<<m  WeQWHXFY

      Birthdate  Phone Number  Store ID  Gender Account Type        Branch
0    1999-09-14  246-425-8359    1603.0  Female     Standard       Oistins
1    1995-10-28  246-570-4150    1721.0    Male     Standard       Oistins
2    2001-04-06  246-673-7216    1276.0   Other        Staff     Six Roads
3    1963-04-24  246-774-9830    1269.0   Other        Staff        Wildey
4    1955-11-24  246-317-9797    1768.0  Female        Staff  Speightstown
..          ...           ...       ...     ...          ...           ...
295         NaN           NaN       NaN     NaN          NaN           NaN
296         NaN           NaN       NaN     NaN          NaN           NaN
297  2002-03-03  246-572-4261    1346.0    Male        Staff        Wildey
298  1961-02-09  246-701-9147    1236.0   Other     Standard    Bridgetown
299  1984-04-10  246-877-9157    1502.0   Other      Premium     Six Roads

[300 rows x 12 columns]>

In [5]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.dbus-keyrings',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.spyder-py3',
 '.vscode',
 'anaconda3',
 'anaconda3-1',
 'anaconda_projects',
 'ansel',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2bece5e1-0114-11f0-969c-a43b759872f7}.TM.blf',
 'NTUSER.DAT{2bece5e1-0114-11f0-969c-a43b759872f7}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2bece5e1-0114-11f0-969c-a43b759872f7}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'pspp.jnl',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Trident Treats_data_analysis.ipynb',
 'Trident Treats_data_analysiscodes.ipynb',
 'TridentTreatsSupermarket2025_totally_real_not_fabricated.csv',
 'TridentTreats_cleaned.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Videos',
 '_avg_']

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("TridentTreatsSupermarket2025_totally_real_not_fabricated.csv")

In [7]:
df.head()

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
0,José Clarke,kendrabest760@tridenttreats.bb,ken41,"36 Grazettes Main Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,1603.0,Female,Standard,Oistins
1,Zoë Callender,aliciajordan285@bdsconnect.bb,ali37,"27 Bank Hall, St. Philip, Barbados",lWmTS:Hf~6,Ih7yfJs1,1995-10-28,246-570-4150,1721.0,Male,Standard,Oistins
2,Renée Best,omarholder876@bdsconnect.bb,oma22,"72 Country Road, St. Philip, Barbados",6>UuVTA\I`,7RPeMOkI,2001-04-06,246-673-7216,1276.0,Other,Staff,Six Roads
3,François Holder,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,1269.0,Other,Staff,Wildey
4,Mårlon Forde,mårlongittens371@bdsconnect.bb,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,1768.0,Female,Staff,Speightstown

In [8]:
df.shape

(300, 12)

In [9]:
df.columns

Index(['Name', 'Email Address', 'Nickname', 'Home Address', 'Password', 'Salt',
       'Birthdate', 'Phone Number', 'Store ID', 'Gender', 'Account Type',
       'Branch'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           300 non-null    object
 1   Email Address  300 non-null    object
 2   Nickname       298 non-null    object
 3   Home Address   298 non-null    object
 4   Password       298 non-null    object
 5   Salt           298 non-null    object
 6   Birthdate      298 non-null    object
 7   Phone Number   298 non-null    object
 8   Store ID       298 non-null    float64
 9   Gender         298 non-null    object
 10  Account Type   298 non-null    object
 11  Branch         298 non-null    object
dtypes: float64(1), object(11)
memory usage: 28.3+ KB

In [11]:
df.describe(include='all')

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
count,300,300,298,298,298,298,298,298,298.000000,298,298,298
unique,203,300,251,263,278,278,276,278,NaN,3,3,5
top,Dario Jordan,kendrabest760@tridenttreats.bb,lat58,"94 Country Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,NaN,Other,Staff,Six Roads
freq,4,1,3,3,2,2,2,2,NaN,106,106,74
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1504.785235,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,284.016208,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1006.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1276.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1751.500000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,NaN,NaN

In [12]:
df.isnull().sum()

Name             0
Email Address    0
Nickname         2
Home Address     2
Password         2
Salt             2
Birthdate        2
Phone Number     2
Store ID         2
Gender           2
Account Type     2
Branch           2
dtype: int64

In [13]:
df[df.isnull().any(axis=1)]

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
295,Devin Holder,devinholder102@caribmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,Alicia Brathwaite,aliciabrathwaite780@tridenttreats.bb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df = df.fillna("Unknown")

In [15]:
df.isnull().sum()

Name             0
Email Address    0
Nickname         0
Home Address     0
Password         0
Salt             0
Birthdate        0
Phone Number     0
Store ID         0
Gender           0
Account Type     0
Branch           0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df = df.drop_duplicates()

In [18]:
df['Name'] = df['Name'].str.title()

In [19]:
df.tail()

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
295,Devin Holder,devinholder102@caribmail.com,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
296,Alicia Brathwaite,aliciabrathwaite780@tridenttreats.bb,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
297,Tanya Holder,tanyaholder917@islandshop.net,tan96,"46 Bank Hall, St. Philip, Barbados",b]!]nY4%[],fhjzzSLg,2002-03-03,246-572-4261,1346.0,Male,Staff,Wildey
298,Kendra Hinds,kendrahinds859@islandshop.net,ken73,"196 Deacons Road, St. Philip, Barbados",|-.I?ZT8\:,8zFGrjXD,1961-02-09,246-701-9147,1236.0,Other,Standard,Bridgetown
299,Kendra Clarke,kendraclarke851@caribmail.com,ken73,"7 St. Philip, St. Philip, Barbados",wW:]PtM<<m,WeQWHXFY,1984-04-10,246-877-9157,1502.0,Other,Premium,Six Roads

In [20]:
df['Birthdate'] = pd.to_datetime(df['Birthdate'], errors='coerce')

In [21]:
df['Gender'] = df['Gender'].str.strip().str.title()
df['Branch'] = df['Branch'].str.strip()
df['Account Type'] = df['Account Type'].str.strip().str.title()

In [22]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [23]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           300 non-null    object
 1   Email Address  300 non-null    object
 2   Nickname       300 non-null    object
 3   Home Address   300 non-null    object
 4   Password       300 non-null    object
 5   Salt           300 non-null    object
 6   Birthdate      298 non-null    datetime64[ns]
 7   Phone Number   300 non-null    object
 8   Store ID       2 non-null      object
 9   Gender         300 non-null    object
 10  Account Type   300 non-null    object
 11  Branch         300 non-null    object
dtypes: datetime64[ns](1), object(11)
memory usage: 28.3+ KB

In [24]:
df.head()

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
0,José Clarke,kendrabest760@tridenttreats.bb,ken41,"36 Grazettes Main Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,NaN,Female,Standard,Oistins
1,Zoë Callender,aliciajordan285@bdsconnect.bb,ali37,"27 Bank Hall, St. Philip, Barbados",lWmTS:Hf~6,Ih7yfJs1,1995-10-28,246-570-4150,NaN,Male,Standard,Oistins
2,Renée Best,omarholder876@bdsconnect.bb,oma22,"72 Country Road, St. Philip, Barbados",6>UuVTA\I`,7RPeMOkI,2001-04-06,246-673-7216,NaN,Other,Staff,Six Roads
3,François Holder,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,NaN,Other,Staff,Wildey
4,Mårlon Forde,mårlongittens371@bdsconnect.bb,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,NaN,Female,Staff,Speightstown

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           300 non-null    object
 1   Email Address  300 non-null    object
 2   Nickname       300 non-null    object
 3   Home Address   300 non-null    object
 4   Password       300 non-null    object
 5   Salt           300 non-null    object
 6   Birthdate      298 non-null    datetime64[ns]
 7   Phone Number   300 non-null    object
 8   Store ID       2 non-null      object
 9   Gender         300 non-null    object
 10  Account Type   300 non-null    object
 11  Branch         300 non-null    object
dtypes: datetime64[ns](1), object(11)
memory usage: 28.3+ KB

In [26]:
df.tail()

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
295,Devin Holder,devinholder102@caribmail.com,Unknown,Unknown,Unknown,Unknown,NaT,Unknown,Unknown,Unknown,Unknown,Unknown
296,Alicia Brathwaite,aliciabrathwaite780@tridenttreats.bb,Unknown,Unknown,Unknown,Unknown,NaT,Unknown,Unknown,Unknown,Unknown,Unknown
297,Tanya Holder,tanyaholder917@islandshop.net,tan96,"46 Bank Hall, St. Philip, Barbados",b]!]nY4%[],fhjzzSLg,2002-03-03,246-572-4261,NaN,Male,Staff,Wildey
298,Kendra Hinds,kendrahinds859@islandshop.net,ken73,"196 Deacons Road, St. Philip, Barbados",|-.I?ZT8\:,8zFGrjXD,1961-02-09,246-701-9147,NaN,Other,Standard,Bridgetown
299,Kendra Clarke,kendraclarke851@caribmail.com,ken73,"7 St. Philip, St. Philip, Barbados",wW:]PtM<<m,WeQWHXFY,1984-04-10,246-877-9157,NaN,Other,Premium,Six Roads

In [27]:
df

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
0,José Clarke,kendrabest760@tridenttreats.bb,ken41,"36 Grazettes Main Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,NaN,Female,Standard,Oistins
1,Zoë Callender,aliciajordan285@bdsconnect.bb,ali37,"27 Bank Hall, St. Philip, Barbados",lWmTS:Hf~6,Ih7yfJs1,1995-10-28,246-570-4150,NaN,Male,Standard,Oistins
2,Renée Best,omarholder876@bdsconnect.bb,oma22,"72 Country Road, St. Philip, Barbados",6>UuVTA\I`,7RPeMOkI,2001-04-06,246-673-7216,NaN,Other,Staff,Six Roads
3,François Holder,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,NaN,Other,Staff,Wildey
4,Mårlon Forde,mårlongittens371@bdsconnect.bb,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,NaN,Female,Staff,Speightstown
...,...,...,...,...,...,...,...,...,...,...,...,...
295,Devin Holder,devinholder102@caribmail.com,Unknown,Unknown,Unknown,Unknown,NaT,Unknown,Unknown,Unknown,Unknown,Unknown
296,Alicia Brathwaite,aliciabrathwaite780@tridenttreats.bb,Unknown,Unknown,Unknown,Unknown,NaT,Unknown,Unknown,Unknown,Unknown,Unknown
297,Tanya Holder,tanyaholder917@islandshop.net,tan96,"46 Bank Hall, St. Philip, Barbados",b]!]nY4%[],fhjzzSLg,2002-03-03,246-572-4261,NaN,Male,Staff,Wildey
298,Kendra Hinds,kendrahinds859@islandshop.net,ken73,"196 Deacons Road, St. Philip, Barbados",|-.I?ZT8\:,8zFGrjXD,1961-02-09,246-701-9147,NaN,Other,Standard,Bridgetown
299,Kendra Clarke,kendraclarke851@caribmail.com,ken73,"7 St. Philip, St. Philip, Barbados",wW:]PtM<<m,WeQWHXFY,1984-04-10,246-877-9157,NaN,Other,Premium,Six Roads

In [28]:
df.to_csv("TridentTreats_cleaned.csv", index=False)

In [29]:
clean_df = pd.read_csv("TridentTreats_cleaned.csv")

In [30]:
clean_df

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
0,José Clarke,kendrabest760@tridenttreats.bb,ken41,"36 Grazettes Main Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,NaN,Female,Standard,Oistins
1,Zoë Callender,aliciajordan285@bdsconnect.bb,ali37,"27 Bank Hall, St. Philip, Barbados",lWmTS:Hf~6,Ih7yfJs1,1995-10-28,246-570-4150,NaN,Male,Standard,Oistins
2,Renée Best,omarholder876@bdsconnect.bb,oma22,"72 Country Road, St. Philip, Barbados",6>UuVTA\I`,7RPeMOkI,2001-04-06,246-673-7216,NaN,Other,Staff,Six Roads
3,François Holder,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,NaN,Other,Staff,Wildey
4,Mårlon Forde,mårlongittens371@bdsconnect.bb,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,NaN,Female,Staff,Speightstown
...,...,...,...,...,...,...,...,...,...,...,...,...
295,Devin Holder,devinholder102@caribmail.com,Unknown,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,Unknown,Unknown
296,Alicia Brathwaite,aliciabrathwaite780@tridenttreats.bb,Unknown,Unknown,Unknown,Unknown,NaN,Unknown,Unknown,Unknown,Unknown,Unknown
297,Tanya Holder,tanyaholder917@islandshop.net,tan96,"46 Bank Hall, St. Philip, Barbados",b]!]nY4%[],fhjzzSLg,2002-03-03,246-572-4261,NaN,Male,Staff,Wildey
298,Kendra Hinds,kendrahinds859@islandshop.net,ken73,"196 Deacons Road, St. Philip, Barbados",|-.I?ZT8\:,8zFGrjXD,1961-02-09,246-701-9147,NaN,Other,Standard,Bridgetown
299,Kendra Clarke,kendraclarke851@caribmail.com,ken73,"7 St. Philip, St. Philip, Barbados",wW:]PtM<<m,WeQWHXFY,1984-04-10,246-877-9157,NaN,Other,Premium,Six Roads

In [31]:
df.loc[263:264]

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
263,Devin Jordan,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,NaN,Other,Staff,Wildey
264,Mårlon Gittens,MÅRLONGITTENS371@BDSCONNECT.BB,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,NaN,Female,Staff,Speightstown

In [32]:
df.loc[265:266]

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
265,Kendra Browne,kendrabrowne446@bdsconnect.bb,ken68,"245 Atlantic Shores, St. Philip, Barbados",}}H#w#n=M>,GMmjxWkI,2004-09-01,246-813-6310,NaN,Male,Standard,Speightstown
266,Omar Hinds,OMARHINDS60@BDSCONNECT.BB,oma82,"22 Silver Sands, St. Philip, Barbados",~!i'qq[8)v,qH3MB9n7,1989-12-23,246-405-6107,NaN,Other,Staff,Speightstown

In [33]:
df.to_csv("TridentTreats_cleaned.csv", index=False)